### ISSUE TITLE
[BUG] Issue with Linear Scale Graph

### ISSUE THREAD

**Issue by aaronleaa** [MunchDev/EpidemicSimulator#20]
When using Linear scales, the graph lines of some countries do not appear on the plotted graph
## Expected Behavior
Graph lines of all countries should appear on the graph

## Current Behavior
Graph lines for some countries do not appear on the graph

## Possible Solution
Check linear scale code for possible errors

## Steps to Reproduce
1. Run console-application.py, World tally plot mode
2. Countries inputted (Singapore, Malaysia, Qatar, China, US) in order
3. Date inputted (04-05-2020)
4. Timespan (40 Days)
5. Plot scale **(linear)**
6. Plot type (cdra)

## Context (Environment)
The issue caused some of the graph lines of some countries to not appear, which affects the overall world tally graph.

## Detailed Description
Trying to plot graphs between countries that have a large number of COVID-19 cases and a low number of COVID-19 cases would cause some graph lines to not display correctly.

## Possible Implementation
N/A

![image](https://user-images.githubusercontent.com/59114002/81104177-b4ace800-8f44-11ea-9b3b-842c784b510e.png)
[Image: **Singapore graph line not showing**]

![image](https://user-images.githubusercontent.com/59114002/81104271-dc03b500-8f44-11ea-8ae4-5ab5994f4daa.png)
[Image: **Singapore and Malaysia graph line not showing**]

![image](https://user-images.githubusercontent.com/59114002/81104317-e9b93a80-8f44-11ea-8c41-64f99d93475a.png)
[Image: **Singapore graph line not showing**]

![image](https://user-images.githubusercontent.com/59114002/81104376-fe95ce00-8f44-11ea-8999-4e67b9cb99c3.png)
[Image: **Singapore and Malaysia graph line not showing**]

**Comment by MunchDev** [comment]
Noted and will work on it.

**Comment by MunchDev** [comment]
Just a gentle reminder, please also report your branch and HEAD refs.

**Comment by MunchDev** [comment]
Errors reproduced successfully, attaching debugger...

**Comment by MunchDev** [comment]
Errors persist when calling function `plot_tally` directly.

**Comment by MunchDev** [comment]
Tested with different countries, the error seems to be due to the render of the plot itself. When trying to use `country = [“Singapore”, “Malaysia”, “China”, “US”]`, Singapore is still visible although the scale is very big. However, when plotted together with Qatar on that scale, Qatar is just a bit higher than Singapore, and as it is plotted after Singapore (as in the order), the plot will be placed in front.

**Comment by MunchDev** [comment]
So this is an external render error with ```matplotlib```. No further action is taken. Case closed!
