### ISSUE TITLE
[FEATURE REQUEST] Provide list of countries supported in README

### ISSUE THREAD

**Issue by aaronleaa** [MunchDev/EpidemicSimulator#22]
**Is your feature request related to a problem? Please describe.**
List of countries may be required so that the user would provide a valid input.

**Describe the solution you'd like**
- Provide list of current supported countries in README.md

**Describe alternatives you've considered**
N/A

**Comment by MunchDev** [comment]
@aaronleaa Do it! Possible solution is to extract from ```cache/population.json```.

**Comment by aaronleaa** [comment]
List of supported countries now provided on README, Req CLOSED.
